export const actiontypes = {
    GET_PRODUCT_DATA:"GET_PRODUCT_DATA",
    INC_QUANTITY:"INC_QUANTITY",
    DEC_QUANTITY:"DEC_QUANTITY",
    FILTER_PRODUCT:"FILTER_PRODUCT",
    CART_ADD_ITEM:"CART_ADD_ITEM",
    REMOVE_FROM_BASKET:"REMOVE_FROM_BASKET"
    
}